apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: system_metrics
    user: admin
    password: admin
    jsonData:
      timeInterval: "5s"
      httpMode: "POST"
      
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: localhost:5432
    database: system_metrics
    user: postgres
    password: postgres
    jsonData:
      sslmode: "disable"
      timescaledb: true
